### ISSUE TITLE
Using PMML with SkLearn's train-test split workflow

### ISSUE THREAD

**Issue by Rico-the-dog** [jpmml/jpmml-evaluator-python#19]
Hi, I'm using sklearn2pmml and jpmml_evaluator for saving and loading sklearn pipeline
My
```python
from sklearn2pmml import sklearn2pmml
from sklearn2pmml.pipeline import PMMLPipeline
col_trans = ColumnTransformer(transformers=[
    ("onehot", OneHotEncoder(handle_unknown="ignore"), ["num_iid","weekday","nick","cid","activity_type","activity_countdown"])
], remainder="passthrough")
gbr = GradientBoostingRegressor(n_estimators=500)
model_pipeline = PMMLPipeline([
    ("preprocess", col_trans),
    ("gbregressor", gbr)
])
model_pipeline.fit(X_train, Y_train)
sklearn2pmml(model_pipeline,'sklearn_pipeline.pmml', with_repr = True)
```
and then read the pmml file:

```python
from jpmml_evaluator import make_evaluator
evaluator = make_evaluator('sklearn_pipeline.pmml')
evaluator.verify()
```

and I got an error:
```
JavaError: org.jpmml.evaluator.EvaluationException: No PMML data type for Java data type null
```

then I tried to evaluate training data:
```python
evaluator.evaluateAll(X_train)
```
It produced all None predictions

In addtion, when I perform:
```python
str([x.getName() for x in evaluator.getInputFields()])
```

I found that the names of remaining columns in ColumnTransformer were missing, they became x3 x4 instead

**Comment by vruusmann** [comment]
Fixed the formatting for you. Don't mess it up again!

**Comment by Rico-the-dog** [comment]
> Fixed the formatting for you. Don't mess it up again!

Thanks a lot

I'm quite confused by this issue, any ideas of solving it?

**Comment by vruusmann** [comment]
> I'm quite confused by this issue, any ideas of solving it?

Wait a moment. I'm writing a comment.

I'm not a chatbot, I need some time for that!

**Comment by vruusmann** [comment]
Long story short - it looks like your SkLearn (PMML-) pipeline is fitted using training data that does not specify **_column names_**.

PMML uses column names for column identification. If the column names are missing, then the PMML engine cannot establish a correct mapping between training and testing dataset columns, and everything goes wrong from here on.

Please note that you're using a tree-based model (`GradientBoostingRegressor`). This makes situation worse, because tree methods only use a subset of training dataset columns. For example, it might be using only every fifth column or so.

**Comment by vruusmann** [comment]
How to fix the situation: convert your `X_train` (and `y_train`) datasets from `numpy.ndarray` to `pandas.DataFrame`, so that correct column names are available.

I assume that you were performing some kind of train-test split in your Python code (right before your sample code starts). So, simply re-wrap `X_train` using column names from the original `X` dataset:

```python
X, y = load_data()

# Expecting to see pandas.DataFrame
print(X.__class__)

X_train, X_test, y_train, y_test = train_test_split(...)

# Expecting to see numpy.ndarray
print(X_train.__class__)

# THIS!
X_train = pandas.DataFrame(X_train, columns = X.columns.values)

# Expecting to see pandas.DataFrame
print(X_train.__class__)

# Proceed as usual.. should be all okay now
```

**Comment by Rico-the-dog** [comment]
> > I'm quite confused by this issue, any ideas of solving it?
> 
> Wait a moment. I'm writing a comment.
> 
> I'm not a chatbot, I need some time for that!

I'm sorry, I didn't mean that...

X_train is a copy of a slice from the original pandas dataframe, it is also a dataframe. Y_train is a Series

**Comment by vruusmann** [comment]
> X_train is a copy of a slice from the original pandas dataframe, it is also a dataframe.

Have you actually tested the type of `X_train`?

How was the slicing done? Using the `sklearn.model_selection.train_test_split()` utility function, or manually?

This utility function used to return `numpy.ndarray` results (eg. `X_train`, `y_train`) when the input was a Pandas' data frame. Maybe it has been updated very recently so that it returns Pandas' data containers now.

**Comment by vruusmann** [comment]
Anyway, the description of your problem is consistent with the "the training dataset is missing column names, so the PMML workflow has trouble mapping columns between train and test" diagnosis.

You'd need to give me more info if you want me to look deeper into this. For example, a reproducible example (dataset plus Python scripts) would be fine. Can you create a "broken example" using the iris dataset?

**Comment by Rico-the-dog** [comment]
> > X_train is a copy of a slice from the original pandas dataframe, it is also a dataframe.
> 
> Have you actually tested the type of `X_train`?
> 
> How was the slicing done? Using the `sklearn.model_selection.train_test_split()` utility function, or manually?
> 
> This utility function used to return `numpy.ndarray` results (eg. `X_train`, `y_train`) when the input was a Pandas' data frame. Maybe it has been updated very recently so that it returns Pandas' data containers now.

Yes, it is pandas.core.frame.DataFrame. I perform all the other feature transforms except one-hot and split it manually. 

Thanks a lot, column name is the problem indeed. I solved it by adding SimpleImputer in ColumnTransformer to transform the rest of the columns. And I found that column name is fixed. No more java errors either. Evaluations also became normal

**Comment by Rico-the-dog** [comment]
> > X_train is a copy of a slice from the original pandas dataframe, it is also a dataframe.
> 
> Have you actually tested the type of `X_train`?
> 
> How was the slicing done? Using the `sklearn.model_selection.train_test_split()` utility function, or manually?
> 
> This utility function used to return `numpy.ndarray` results (eg. `X_train`, `y_train`) when the input was a Pandas' data frame. Maybe it has been updated very recently so that it returns Pandas' data containers now.

Yes, it is pandas.core.frame.DataFrame. I perform all the other feature transforms except one-hot and split it manually. 

Thanks a lot, column name is the problem indeed. I solved it by adding SimpleImputer in ColumnTransformer to transform the rest of the columns. And I found that column name is fixed. No more java errors either. Evaluations also became normal

**Comment by vruusmann** [comment]
> Thanks a lot, column name is the problem indeed.

The converter should be issuing a Python warning if column names are missing (something like: "Attribute PMMLPipeline.active_fields is not set. Assuming ...").

You don't want to get any warnings during conversion - signals that the pipeline/workflow is fragile.

> I solved it by adding SimpleImputer in ColumnTransformer to transform the rest of the columns.

You mean you replaced `ColumnTransformer(..., remainder = "passthrough")` with `ColumnTransformer(..., remainder = SimpleImputer())`?

The `remainder = "passthrough"` configuration should be fine from the PMML conversion perspective.

**Comment by vruusmann** [comment]
> The converter should be issuing a Python warning if column names are missing

You can always set this attribute manually (instead of wrapping `X_train` and `y_train` objects):

```python
pipeline = PMMLPipeline(...)
# Fitting using numpy.ndarray data containers - missing column names
pipeline.fit(X_train, y_train)

# THIS
pipeline.active_fields = numpy.asarray(X.columns.values)
pipeline.target_fields = numpy.asarray(y.name)
```

**Comment by Rico-the-dog** [comment]
> > Thanks a lot, column name is the problem indeed.
> 
> The converter should be issuing a Python warning if column names are missing (something like: "Attribute PMMLPipeline.active_fields is not set. Assuming ...").
> 
> You don't want to get any warnings during conversion - signals that the pipeline/workflow is fragile.
> 
> > I solved it by adding SimpleImputer in ColumnTransformer to transform the rest of the columns.
> 
> You mean you replaced `ColumnTransformer(..., remainder = "passthrough")` with `ColumnTransformer(..., remainder = SimpleImputer())`?
> 
> The `remainder = "passthrough"` configuration should be fine from the PMML conversion perspective.

There were no python warnings. The ColumnTransformer now is:
```
col_trans = ColumnTransformer(transformers=[
    ("onehot", OneHotEncoder(handle_unknown="ignore"), ["num_iid","weekday","nick","cid","activity_type","activity_countdown"]),
    ("imputer", SimpleImputer(), ["cost","recent_gmv"])
])
```
It seems that `remainder = "passthrough"` will lead to the problem
