### ISSUE TITLE
Advice for debugging erroneous input and/or PMML documents

### ISSUE THREAD

**Issue by axemixer** [jpmml/jpmml-evaluator-python#20]
Hi ,

I'm trying to run pmml file from jpmm_evaluator and it gives me an error as below : 

`  File "PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jpmml_evaluator\__init__.py", line 156, in evaluate
    raise self.backend.toJavaError(e)
jpmml_evaluator.JavaError: java.lang.NumberFormatException: empty String`

I sent all information with arguments ( no Empty string) but Is there any way to detect which field or fields cause this error or which part of pmml file ?

**Comment by vruusmann** [comment]
> I sent all information with arguments (no Empty string)

How do you know that?

The fault is in your Python code. Probably somewhere around loading the dataset from a CSV file.

> Is there any way to detect which field or fields cause this error or which part of pmml file?

Iterate over your dataset in a row-by-row manner - ie. using the `Evaluator.evaluate(X)` method, not the `Evaluator.evaluateAll(X)` method. When the evaluation raises this NumberFormatException, print out the contents of the `X` argument, and you shall have your mystery solved.

Alternatively, evaluate the PMML + CSV combo using the JPMML-Evaluator command-line application:
https://github.com/jpmml/jpmml-evaluator#example-applications

**Comment by axemixer** [comment]
Actually , I'm passing only one record to pmml with below code 

```python
from jpmml_evaluator import make_evaluator

evaluator = make_evaluator("MY_PMML.pmml") \
	.verify()

arguments = {
	"A" : 1,
	"B" : 20,
	"C" : "E"
}

results = evaluator.evaluate(arguments)
print(results)
```

But I get only empty String Error but I've supplied to every necessary field for regression model.

Do we have any chance to detect which line of pmml file threat the error ?

**Comment by vruusmann** [comment]
> Actually , I'm passing only one record to pmml with below code

Actually, this code example me think that the problem is not about the input data record, but the PMML document itself.

The PMML contains invalid markup - the value of some numeric attribute has been left empty (specifically, the attribute has been set to an empty value like `<MyElement myattribute="">` when it should have been omitted like `<MyAttribute/>`).

The exception is raised in the PMML document loading/pre-parsing phase, not the evaluation phase.

> Do we have any chance to detect which line of pmml file threat the error ?

Did you run your sample using the JPMML-Evaluator command-line application like I told you above? This would print the Java exception stack trace straight into the console, which would show the Java method/code path where the problem occurs - will be easy to see if it's related to input data record or PMML document.

Please don't waste my time to make me guess about "what might me wrong". You can have a definite answer available in less than a minute.

**Comment by vruusmann** [comment]
>  This would print the Java exception stack trace straight into the console, which would show the Java method/code path where the problem occurs

Also, this information is readily available in the `jpmml_evaluator.JavaError` object that you can catch in your Python application code:
https://github.com/jpmml/jpmml-evaluator-python/blob/0.10.0/jpmml_evaluator/__init__.py#L81-L95

Something like this:
```python
from jpmml_evaluator import JavaError

evaluator = make_evaluator(...)

try:
  evaluator.evaluate(X)
except JavaError as je:
  print(je)
```
