### ISSUE TITLE
Index of evaluateAll  output DF does not match that of input

### ISSUE THREAD

**Issue by terr01** [jpmml/jpmml-evaluator-python#23]
The output dataframe is created with default `RangeIndex`. A quick fix is to create the output like this instead
```python
results_df = DataFrame(
    data = results_dict["data"], 
    columns = results_dict["columns"], 
    index=arguments_df.index
)
```

**Comment by vruusmann** [comment]
Noted.

This fix would make a metadata-level connection between these two `DataFrame` objects:
https://github.com/jpmml/jpmml-evaluator-python/blob/0.10.1/jpmml_evaluator/__init__.py#L164
https://github.com/jpmml/jpmml-evaluator-python/blob/0.10.1/jpmml_evaluator/__init__.py#L175

Most ML models perform a 1-to-1 mapping (ie. one row of input produces one row of output). But it wouldn't hurt to have a quick check about this assumption, and fall back to a default numbering of output rows if it's being violated.

**Comment by terr01** [comment]
Thanks. Shouldn't there be a meta-level connection between these two objects?  i.e. 
```python
evaluateAll(df) shouldBeSameAs df.apply(lambda row: evaluate(row), axis=1) #probably with result_type = "expand"
```
This connection would break if `df` can be split into one or more groups and the predictions for each group are based on that group's data as a whole.  But this (and others such) seems like entirely different use-case that probably deserves its own function.

**Comment by vruusmann** [comment]
> `evaluateAll(df)` shouldBeSameAs `df.apply(lambda row: evaluate(row), axis=1)`
>

The `evaluateAll(df)` method call involves exactly one Python-Java-Python roundtrip, because all data is sent over in one go (as a `dict` data structure). If you replace it with elementary `evaluate(X)` method calls, then there will be many Python-Java-Python roundtrips (one for each data frame row).

It is my guesstimate that the computational cost of Python-Java-Python rountrip could be comparable to the cost of the actual model evaluation work. So, by limiting the number of roundtrips, I'm expecting to get more "useful" work done per unit of time.

For reference, here's the mechanics of a Python-Java-Python roundtrip:

1. In Python, dump arguments in `pickle` data format to a pickle blob (byte array).
2. Send the pickle blob from Python to Java.
3. In Java, load arguments from pickle blob.
4. In Java, perform model evaluation.
5. In Java, dump results in `pickle` data format to a pickle blob.
6. Send the pickle blob from Java to Python.
7. In Python, load results from pickle blob.
