### ISSUE TITLE
Setting JAVA_HOME required although java is installed in PATH

### ISSUE THREAD

**Issue by maxnoe** [jpmml/jpmml-evaluator-python#3]
I'm having trouble running this on travis for unit tests.

* Java 8 is installed and in the PATH.
* Not setting `JAVA_HOME` directly results in a python `KeyError`
* Setting it to the base of the JDK or JRE on travis results in looking at the wrong path, see build log here: https://travis-ci.org/fact-project/aict-tools/jobs/550851228

**Comment by maxnoe** [comment]
Sorry, this is a pyjnius problem.

**Comment by vruusmann** [comment]
> Sorry, this is a pyjnius problem.

I would suggest using the Py4J gateway right now, because the PyJNIus gateway is currently unusable due to a method resolution bug therein.

Been waiting for a PyJNIus release since mid-Feb, but it's not happening. Specifically, need this commit: https://github.com/kivy/pyjnius/commit/b748257a66a3391d712a214897e1a1f3097ac466

**Comment by maxnoe** [comment]
Thanks for the fast reply. I'm also having problems with py4j now on travis.

Locally on my Ubuntu 18.04 both backends work fine. Any idea:

https://travis-ci.org/fact-project/aict-tools/jobs/551247957 ?

**Comment by vruusmann** [comment]
> Any idea: https://travis-ci.org/fact-project/aict-tools/jobs/551247957 ?

Looks like the `LoadingModelEvaluatorBuilder#setLocatable(boolean)` is either not found, or is returning an unexpected value (eg. `void` instead of a self reference).

The most probable cause is some sort of JPMML-Evaluator library version issue. For example, have you replaced the default version with the latest one (1.4.11) in your CI environment?

Should really update JPMML-Evaluator-Python myself. However, if I do so, I can't push it to GitHub as an "endorsed state" because of that PyJNIus bug.

**Comment by maxnoe** [comment]
Ah, I installed from github master. I'll try with the latest release version. 
However, on my machine it worked fine, just travis is not working.

**Comment by maxnoe** [comment]
No, does not work either, the last release does not even have the `make_evaluator` function

**Comment by maxnoe** [comment]
Ah, sorry you are talking about the jpmml library itself. How do I install a certain version of it? I just assumed it came with this library.
